import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        // SCENTORA Color Palette
        scentora: {
          beige: '#F5F0E8',
          dark: '#1A1A1A',
          'dark-secondary': '#2D2D2D',
          accent: '#E8354A',
          'gold-amber': '#D4A843',
          'gold-light': '#C68B2A',
          'gold-dark': '#8B5E1A',
          purple: '#4A1A6B',
          'purple-dark': '#2D0D4A',
          pink: '#C4185A',
          'pink-dark': '#8B0D3A',
          teal: '#0D4A4A',
          'teal-dark': '#1A2D2D',
          blue: '#1B3A6B',
          'blue-dark': '#0D1F3C',
        },
        perfume: {
          50: '#fdf2f8',
          100: '#fce7f3',
          200: '#fbcfe8',
          300: '#f9a8d4',
          400: '#f472b6',
          500: '#ec4899',
          600: '#db2777',
          700: '#be185d',
          800: '#9d174d',
          900: '#831843',
          950: '#500724',
        },
        oud: {
          50: '#faf5ff',
          100: '#f3e8ff',
          200: '#e9d5ff',
          300: '#d8b4fe',
          400: '#c084fc',
          500: '#a855f7',
          600: '#9333ea',
          700: '#7e22ce',
          800: '#6b21a8',
          900: '#581c87',
          950: '#3b0764',
        },
        gold: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
          950: '#451a03',
        },
        cream: {
          50: '#fefdfb',
          100: '#fdf9f3',
          200: '#faf3e8',
          300: '#f5e6d3',
        },
      },
      fontFamily: {
        sans: ['var(--font-jost)', 'Jost', 'DM Sans', 'system-ui', 'sans-serif'],
        serif: ['var(--font-playfair)', 'Playfair Display', 'Georgia', 'serif'],
        display: ['var(--font-playfair)', 'Playfair Display', 'Georgia', 'serif'],
        'heading': ['Abril Fatface', 'Cormorant Garamond', 'Georgia', 'serif'],
      },
      fontSize: {
        'scentora-xs': ['11px', { lineHeight: '14px' }],
        'scentora-sm': ['13px', { lineHeight: '18px' }],
        'scentora-base': ['14px', { lineHeight: '20px' }],
        'scentora-price': ['15px', { lineHeight: '20px', fontWeight: '700' }],
        'scentora-h1': ['52px', { lineHeight: '56px', fontWeight: '900' }],
        'scentora-nav': ['13px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      borderRadius: {
        lg: '16px',
        md: '12px',
        sm: '8px',
        'xl': '20px',
        '2xl': '24px',
        'full': '9999px',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        fadeIn: {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        shimmer: 'shimmer 2s linear infinite',
        'fade-in': 'fadeIn 0.5s ease-out forwards',
        'float': 'float 3s ease-in-out infinite',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-perfume': 'linear-gradient(135deg, #ec4899 0%, #a855f7 50%, #f59e0b 100%)',
        'gradient-luxury': 'linear-gradient(135deg, #831843 0%, #581c87 50%, #78350f 100%)',
        'card-blue': 'linear-gradient(135deg, #1B3A6B 0%, #0D1F3C 100%)',
        'card-dark': 'linear-gradient(135deg, #1A1A1A 0%, #2D2D2D 100%)',
        'card-amber': 'linear-gradient(135deg, #C68B2A 0%, #8B5E1A 100%)',
        'card-purple': 'linear-gradient(135deg, #4A1A6B 0%, #2D0D4A 100%)',
        'card-pink': 'linear-gradient(135deg, #C4185A 0%, #8B0D3A 100%)',
        'card-teal': 'linear-gradient(135deg, #0D4A4A 0%, #1A2D2D 100%)',
        'scentora-gradient': 'linear-gradient(135deg, #ec4899 0%, #a855f7 50%, #f59e0b 100%)',
      },
      boxShadow: {
        'scentora': '0 8px 32px rgba(0,0,0,0.12)',
        'scentora-lg': '0 16px 48px rgba(0,0,0,0.2)',
        'scentora-sm': '0 4px 16px rgba(0,0,0,0.08)',
        'gold': '0 4px 20px rgba(245, 158, 11, 0.25)',
        'scentora-warm': '0 4px 20px rgba(0,0,0,0.10)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};

export default config;
